#!/usr/bin/perl -w

use strict;

my @files = @ARGV;
my $max = @files - 1;

foreach my $a (0 .. $max - 2)
{
  my $aa = $files[$a];
  foreach my $b ($a + 1 .. $max - 1)
  {
    my $bb = $files[$b];
    foreach my $c ($b + 1 .. $max)
    {
      my $cc = $files[$c];

      my $batch = `mars $aa $bb $cc`;
      print "$batch\n";
    }
  }
}
